address = "0.0.0.0:8030"
image_folder = "images/"
auth_file = "/run/secrets/AUTH_FILE"

[database]
name = { path = "/run/secrets/POSTGRES_DB" }
username = { path = "/run/secrets/POSTGRES_USER" }
password = { path = "/run/secrets/POSTGRES_PASSWORD" }
address = { value = "database:5432" }
